# 创建数组

In [1]:
import numpy as np

## 通过list创建

In [2]:
a = np.array([[1, 2, 3], [2, 3, 4]])
a

array([[1, 2, 3],
       [2, 3, 4]])

In [3]:
# 查看数组形状，是一个2行、3列的数组
a.shape

(2, 3)

## 创建常见数组

In [4]:
# 创建指定形状，元素全为0的数组
np.zeros((4, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [5]:
# 元素全为1的数组
np.ones((2, 3, 4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [6]:
# 创建等差数列，参数为(start, end, step)
np.arange(1, 10, 2)

array([1, 3, 5, 7, 9])

In [7]:
# 创建等差数列，参数为(start, end, number)
np.linspace(0, 2, 5)

array([0. , 0.5, 1. , 1.5, 2. ])

## 指定数据类型

In [8]:
# 查看数组数据类型
a.dtype

dtype('int64')

In [9]:
# 创建数组时指定数据类型
x = np.ones((2, 3), dtype=np.float32)
x.dtype

dtype('float32')

In [10]:
# 通过astype改变数据类型，必须赋值才可以
x = x.astype(np.float64)
x.dtype

dtype('float64')

## 随机数组

In [11]:
# 指定size的[0, 1)间均匀分布
np.random.random(10), np.random.rand(3, 2)

(array([0.28629553, 0.85144019, 0.539049  , 0.13156584, 0.96596042,
        0.52049636, 0.60842881, 0.19406661, 0.32719927, 0.66816377]),
 array([[0.97447055, 0.79019727],
        [0.87802541, 0.83311124],
        [0.11892436, 0.04404554]]))

In [12]:
# 标准正态分布
np.random.randn(2, 3)

array([[-0.58181851, -0.32709059, -0.86756153],
       [ 1.08933616,  0.59254547,  0.25114256]])

In [13]:
# 正态分布，参数为(mean, std, size)
np.random.normal(1, 2, (2, 2))

array([[-0.9295748 , -0.73332686],
       [ 0.83600881, -3.03588061]])

In [14]:
# 多维正态分布，参数为(mean, covariance, size)
np.random.multivariate_normal([0, 0], [[2, 1], [1, 3]], 10)

array([[ 0.39811736, -2.70838167],
       [ 0.08234322, -0.49231645],
       [ 1.41958411, -0.15348252],
       [-0.33857996, -0.80741785],
       [-1.14372373, -1.06497689],
       [ 0.49957642,  0.15332896],
       [ 1.69891772,  2.06578552],
       [ 0.37780795,  2.5950782 ],
       [ 0.30047815,  0.54986861],
       [-0.63135852, -0.25995852]])

In [15]:
# 随机整数，参数为(low, high, size)
np.random.randint(0, 4, 10)

array([0, 2, 1, 3, 1, 0, 0, 3, 0, 2])

In [16]:
# 固定随机数种子，有助于复现，固定随机数种子为1后，下一个 np.random.random() 必定为 0.417022004702574
np.random.seed(1)
np.random.random()

0.417022004702574