# 聚合

## 常用聚合函数

In [1]:
import numpy as np

x = np.random.rand(3, 2)
x

array([[0.45785682, 0.60140321],
       [0.90493417, 0.56003275],
       [0.17515824, 0.32652628]])

In [2]:
np.sum(x), np.mean(x) # 和值、平均值

(3.0259114733147117, 0.5043185788857852)

In [3]:
np.min(x), np.max(x) # 最小值、最大值

(0.1751582395918695, 0.904934174169447)

In [4]:
np.median(x), np.percentile(x, 20) # 中位数、百分之20分位数

(0.508944785499847, 0.32652627687634117)

## 多维度聚合

In [5]:
np.max(x, axis=0) # 行间进行比较，axis=0即行这个维度消失

array([0.90493417, 0.60140321])

In [6]:
y = np.random.randn(2, 3, 4)
y

array([[[ 1.3386713 ,  1.94910124,  1.25339686, -0.42422309],
        [-1.29489483, -0.32559544, -0.05254653, -1.21260872],
        [-0.99998806,  0.905526  , -0.72435857,  1.30388311]],

       [[ 0.39234866,  0.89437761, -0.60706913, -1.13116912],
        [-1.24819303, -0.73130412,  0.74239654, -0.32840019],
        [ 0.73436036, -0.54511568, -1.12935876,  1.31477908]]])

In [7]:
y.sum(axis=1) # 另一种写法，axis=1的维度消失

array([[-0.95621158,  2.52903179,  0.47649177, -0.3329487 ],
       [-0.12148401, -0.38204219, -0.99403136, -0.14479024]])