# 聚合

In [1]:
import numpy as np

## 常用聚合函数

In [2]:
x = np.random.rand(3, 2)
x

array([[0.3625344 , 0.52834057],
       [0.79060661, 0.54813746],
       [0.96487014, 0.44936943]])

In [3]:
# 和值、平均值
np.sum(x), np.mean(x)

(3.6438586188949498, 0.607309769815825)

In [4]:
# 最小值、最大值
np.min(x), np.max(x)

(0.3625344023631736, 0.9648701396391192)

In [5]:
# 中位数、百分之20分位数
np.median(x), np.percentile(x, 20)

(0.5382390155529406, 0.4493694314922795)

## 多维度聚合

In [6]:
# 行间进行比较，axis=0即行这个维度消失
np.max(x, axis=0)

array([0.96487014, 0.54813746])

In [7]:
y = np.random.randn(2, 3, 4)
y

array([[[-0.51175823, -0.81631805,  0.98893297, -0.46842245],
        [-0.66681349, -1.87308632, -0.74330891,  0.84523067],
        [-0.56810221, -0.78825293,  0.91901952,  1.43554707]],

       [[-0.65903731,  0.42256817, -1.39494768,  1.09175511],
        [ 0.48787191,  0.5874    , -0.78485112, -0.01057017],
        [-0.26008409,  0.41747973, -0.31438493, -0.83971824]]])

In [8]:
# 另一种写法，axis=1的维度消失
y.sum(axis=1)

array([[-1.74667393, -3.4776573 ,  1.16464358,  1.81235529],
       [-0.43124949,  1.42744791, -2.49418373,  0.24146669]])