# 索引、切片

In [1]:
import numpy as np

## 索引

In [2]:
a = np.array([[1, 2, 3], [4, 5, 6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [3]:
# 获取数组第i个值
a[0, 1], a[0][1]

(2, 2)

In [4]:
# 通过负值索引获得数组末尾的值，修改元素值
a[1, -1] = 10
a

array([[ 1,  2,  3],
       [ 4,  5, 10]])

In [5]:
# 第2行
a[1]

array([ 4,  5, 10])

## 数组切片

In [6]:
# 第1列
a[:, 0]

array([1, 4])

In [7]:
# 即切行，也切列
a[: , : 2]

array([[1, 2],
       [4, 5]])