# 聚合

In [1]:
import numpy as np

## 常用聚合函数

In [2]:
x = np.random.rand(3, 2)
x

array([[0.90300215, 0.08848348],
       [0.20936519, 0.50194978],
       [0.5676958 , 0.63503255]])

In [3]:
# 和值、平均值
np.sum(x), np.mean(x)

(2.9055289496594705, 0.48425482494324507)

In [4]:
# 最小值、最大值
np.min(x), np.max(x)

(0.08848347978571902, 0.9030021458449725)

In [5]:
# 中位数、百分之20分位数
np.median(x), np.percentile(x, 20)

(0.5348227926329352, 0.20936519213972438)

## 多维度聚合

In [6]:
# 行间进行比较，axis=0即行这个维度消失
np.max(x, axis=0)

array([0.90300215, 0.63503255])

In [7]:
y = np.random.randn(2, 3, 4)
y

array([[[-0.6846808 ,  0.48764783, -0.60375202, -1.32191235],
        [ 1.84617581, -0.79173978, -0.05001338, -0.15421224],
        [ 0.91426081,  1.1192568 ,  0.17319568, -0.28206962]],

       [[ 1.00876682, -0.39765289,  0.82469207, -0.10270196],
        [-1.03272217, -1.0899653 ,  1.45619415, -1.91285332],
        [ 1.15643837,  0.23364239,  1.44771119, -1.61790942]]])

In [8]:
# 另一种写法，axis=1的维度消失
y.sum(axis=1)

array([[ 2.07575583,  0.81516485, -0.48056972, -1.75819421],
       [ 1.13248302, -1.2539758 ,  3.72859741, -3.6334647 ]])