# 创建数组

In [1]:
import numpy as np

## 通过list创建

In [2]:
a = np.array([[1, 2, 3], [2, 3, 4]])
a

array([[1, 2, 3],
       [2, 3, 4]])

In [3]:
# 查看数组形状，是一个2行、3列的数组
a.shape

(2, 3)

## 创建常见数组

In [4]:
# 创建指定形状，元素全为0的数组
np.zeros((4, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [5]:
# 元素全为1的数组
np.ones((2, 3, 4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [6]:
# 创建等差数列，参数为(start, end, step)
np.arange(1, 10, 2)

array([1, 3, 5, 7, 9])

In [7]:
# 创建等差数列，参数为(start, end, number)
np.linspace(0, 2, 5)

array([0. , 0.5, 1. , 1.5, 2. ])

## 指定数据类型

In [8]:
# 查看数组数据类型
a.dtype

dtype('int64')

In [9]:
# 创建数组时指定数据类型
x = np.ones((2, 3), dtype=np.float32)
x.dtype

dtype('float32')

In [10]:
# 通过astype改变数据类型，必须赋值才可以
x = x.astype(np.float64)
x.dtype

dtype('float64')

## 随机数组

In [11]:
# 指定size的[0, 1)间均匀分布
np.random.random(10), np.random.rand(3, 2)

(array([0.96410309, 0.62551081, 0.09910126, 0.64749452, 0.1897011 ,
        0.90333034, 0.09482946, 0.13742104, 0.88985448, 0.38732618]),
 array([[0.98215139, 0.9474577 ],
        [0.91167319, 0.47013592],
        [0.43555484, 0.41824094]]))

In [12]:
# 标准正态分布
np.random.randn(2, 3)

array([[-0.66820881,  0.55374248,  0.4395415 ],
       [-2.00977898,  0.64799851, -0.4217015 ]])

In [13]:
# 正态分布，参数为(mean, std, size)
np.random.normal(1, 2, (2, 2))

array([[ 1.10346974,  1.89666007],
       [-1.17095914,  2.31074179]])

In [14]:
# 多维正态分布，参数为(mean, covariance, size)
np.random.multivariate_normal([0, 0], [[2, 1], [1, 3]], 10)

array([[-1.05710149, -2.69121989],
       [-1.08521534, -1.66291162],
       [-0.20980566, -1.28101636],
       [ 2.00241579,  0.3434247 ],
       [ 3.70496984,  1.11017336],
       [-2.80922866, -0.51345142],
       [-1.39144457,  0.12309069],
       [-1.55454993, -3.97629639],
       [-3.27334244,  1.00143544],
       [ 2.18268257, -2.3265939 ]])

In [15]:
# 随机整数，参数为(low, high, size)
np.random.randint(0, 4, 10)

array([2, 2, 2, 1, 3, 3, 3, 3, 0, 1])

In [16]:
# 固定随机数种子，有助于复现，固定随机数种子为1后，下一个 np.random.random() 必定为 0.417022004702574
np.random.seed(1)
np.random.random()

0.417022004702574