# 创建数组

## 通过list创建

In [1]:
import numpy as np

a = np.array([[1, 2, 3], [2, 3, 4]])
a

array([[1, 2, 3],
       [2, 3, 4]])

In [2]:
# 查看数组形状，是一个2行、3列的数组
a.shape

(2, 3)

## 创建常见数组

In [3]:
# 创建指定形状，元素全为0的数组
np.zeros((4, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [4]:
# 元素全为1的数组
np.ones((2, 3, 4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [5]:
# 创建等差数列，参数为(start, end, step)
np.arange(1, 10, 2)

array([1, 3, 5, 7, 9])

In [6]:
# 创建等差数列，参数为(start, end, number)
np.linspace(0, 2, 5)

array([0. , 0.5, 1. , 1.5, 2. ])

## 指定数据类型

In [7]:
# 查看数组数据类型
a.dtype

dtype('int64')

In [8]:
# 创建数组时指定数据类型
x = np.ones((2, 3), dtype=np.float32)
x.dtype

dtype('float32')

In [9]:
# 通过astype改变数据类型，必须赋值才可以
x = x.astype(np.float64)
x.dtype

dtype('float64')

## 随机数组

In [10]:
# 指定size的[0, 1)间均匀分布
np.random.random(10), np.random.rand(3, 2)

(array([0.69092445, 0.35609476, 0.12446675, 0.96774025, 0.76863684,
        0.67593351, 0.65382843, 0.15768341, 0.32360781, 0.28010004]),
 array([[0.99956203, 0.00776139],
        [0.95888325, 0.38752896],
        [0.51025826, 0.84065792]]))

In [11]:
# 标准正态分布
np.random.randn(2, 3)

array([[-0.16872531, -0.6103349 , -0.24893244],
       [-0.2571486 , -0.95528456,  0.95426718]])

In [12]:
# 正态分布，参数为(mean, std, size)
np.random.normal(1, 2, (2, 2))

array([[-0.91248195, -1.84457807],
       [ 1.72175898, -0.86299705]])

In [13]:
# 多维正态分布，参数为(mean, covariance, size)
np.random.multivariate_normal([0, 0], [[2, 1], [1, 3]], 10)

array([[ 2.53344902,  0.13154714],
       [-0.30001733,  4.27624571],
       [ 0.7622491 ,  1.57187328],
       [ 0.28646588, -0.46075151],
       [ 1.5746347 , -2.04449022],
       [ 1.41066807, -1.8562889 ],
       [-0.41319555, -1.31518066],
       [ 2.31274919,  1.52219926],
       [-2.91856425, -0.34996747],
       [ 0.63412347, -0.95510824]])

In [14]:
# 随机整数，参数为(low, high, size)
np.random.randint(0, 4, 10)

array([2, 3, 1, 0, 2, 0, 0, 1, 3, 1])

In [15]:
# 固定随机数种子，有助于复现
np.random.seed(1)
# 固定随机数种子为1后，下一个np.random.random()必定为0.417022004702574
np.random.random()

0.417022004702574