# 比较、布尔索引和排序

In [1]:
import numpy as np

## 比较得到 bool 型数组

In [2]:
x = np.arange(6)
x

array([0, 1, 2, 3, 4, 5])

In [3]:
# 各个元素是否小于3
x < 3

array([ True,  True,  True, False, False, False])

In [4]:
# 各个元素是否满足等式
(2 ** x) == (x ** 2)

array([False, False,  True, False,  True, False])

In [5]:
# 大于等于1的元素个数
np.sum(x >= 1)

5

In [6]:
# 是否有元素为0
np.any(x == 0)

True

In [7]:
# 是否所有元素都大于0
np.all(x > 0)

False

In [8]:
# 多个条件，是否是[1, 4]间的数
(x >= 1) & (x <= 4)

array([False,  True,  True,  True,  True, False])

## bool 型数组作为索引

In [9]:
x[~((x > 4) | (x <= 2)) ]

array([3, 4])

## 排序

In [10]:
np.random.seed(0)
a = np.random.randint(0, 10, 5)
a

array([5, 0, 3, 3, 7])

In [11]:
# 将a排序后数组，原数组a未改变
np.sort(a)

array([0, 3, 3, 5, 7])

In [12]:
# 从小到大的元素索引值
np.argsort(a)

array([1, 2, 3, 0, 4])

In [13]:
# 使用np.argsort(a)作为索引
a[np.argsort(a)]

array([0, 3, 3, 5, 7])

In [14]:
# 排序并改变原数组
a.sort()
a

array([0, 3, 3, 5, 7])